---
spec/spec_helper.rb:
  mock_with: ":mocha"
.travis.yml:
  branches:
    - main
    - /^v\d/
  user: "optiz0r"
  secure: "j/1VCpnJieB6rnOdzQiFUau94WjwGiU9ZRxqAqCiJ9wXbeufyyGJ+C780ysOptwNTKq0K61rfdUfiyJZDcTXFH+jEN/Ia/VRpVuo9lgTo/JU7irIJOHaB1EMvgzJxeDMWY7XwKu+06xSNnqhCrGJEZ3FU5pW1Co/tHYWknlHg9dFdkXU5r5CRcfzSkz0abynenvAOg7uUEZw3qhli22U0CMeMDSL47Dy/I+CQWcynE+AvZ3k5W+WTlbnJq10cJWChlpPWYXFEPH7Mj75LMAlSRoLf3oSiAAy6xklvUUZHjxIvGWMXud2It3acGIEIVwrO87kGno36eMSIRwKTRsaxG77ciKheQpJ3iAruRAwgQh0PhdaQJ3GsEftQ0T5fdRjnVXcDLJV9SvDrau20PoHdLwNSDcW/Y8rsCUFThf3Te02NjR3rdC/I3iHb+2i4T2FxtLi0W305Lcq9VdFdNsN8lG/QVRx9YT0Q4B789IUiFQTY8Y6nToFfssPNZETsKKWOPCSTQ0JUCUzvVQyiGEYUNW4VWPArnV3dteC45ZNV3rCjTv63Ni59mmyUWyV7/pWjuComQD7dx/ixMaCtyZMpUCGg6GM08wZWLTRvYr8HitUa1MLYR2cJ3VMGYJz2wIo4Sn4dKnc7yH9qKgoiCgPjj3FmW67PcLj2ITk6Xmza1A="
